# Generated by Django 5.2.7 on 2026-02-06 19:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                ("filename", models.CharField(db_index=True, max_length=255)),
                ("nodes_data", models.JSONField()),
                ("edges_data", models.JSONField()),
                ("propositions", models.JSONField(blank=True, null=True)),
                ("total_nodes", models.IntegerField(default=0)),
                ("total_edges", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CMEvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                (
                    "evaluation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "final_score",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("comments_proposition", models.TextField(blank=True, null=True)),
                (
                    "comments_topological_scoring",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "comments_structure_classification",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "concept_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="comea_app.conceptmap",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropositionRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                (
                    "propositions_classification",
                    models.JSONField(blank=True, null=True),
                ),
                ("propositions_correction", models.JSONField(blank=True, null=True)),
                ("completeness_score", models.FloatField(default=0.0)),
                ("correctness_score", models.FloatField(default=0.0)),
                ("completeness_specification", models.JSONField(blank=True, null=True)),
                ("proposition_specification", models.JSONField(blank=True, null=True)),
                ("proposition_score", models.FloatField(default=0.0)),
                (
                    "concept_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposition_rubrics",
                        to="comea_app.conceptmap",
                    ),
                ),
                (
                    "evaluation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposition_rubrics",
                        to="comea_app.cmevaluationresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cmevaluationresult",
            name="proposition_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluation_results",
                to="comea_app.propositionrubric",
            ),
        ),
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                ("filename", models.CharField(db_index=True, max_length=255)),
                ("full_text", models.TextField()),
                ("nodes_data", models.JSONField(blank=True, null=True)),
                ("edges_data", models.JSONField(blank=True, null=True)),
                ("propositions", models.JSONField(blank=True, null=True)),
                ("propositions_weight", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RubricConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("proposition_rubric_checkbox", models.BooleanField(default=False)),
                (
                    "topological_scoring_rubric_checkbox",
                    models.BooleanField(default=False),
                ),
                ("half_correct", models.BooleanField(default=True)),
                ("structure_classification", models.BooleanField(default=True)),
                (
                    "proposition_weight",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "topological_scoring_weight",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "topological_level_configuration",
                    models.JSONField(blank=True, null=True),
                ),
                (
                    "reference_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="The reference document associated with this configuration",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comea_app.referencedocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created this configuration",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="cmevaluationresult",
            name="rubric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="comea_app.rubricconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="StructureClassificationRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                ("node_colors", models.JSONField(blank=True, null=True)),
                (
                    "size_spokes_threshold",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "size_chain_threshold",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("concept_map_image", models.TextField(blank=True, null=True)),
                ("description", models.JSONField(blank=True, null=True)),
                (
                    "concept_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_classification_rubrics",
                        to="comea_app.conceptmap",
                    ),
                ),
                (
                    "evaluation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structure_classification_rubrics",
                        to="comea_app.cmevaluationresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cmevaluationresult",
            name="structure_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluation_results",
                to="comea_app.structureclassificationrubric",
            ),
        ),
        migrations.CreateModel(
            name="TopologicalScoringRubric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modified", models.BooleanField(default=False)),
                ("long_text_nodes", models.IntegerField(default=0)),
                ("long_text_nodes_description", models.TextField(default="")),
                ("edges_without_link_word", models.IntegerField(default=0)),
                ("edges_without_link_word_description", models.TextField(default="")),
                ("branching_points", models.IntegerField(default=0)),
                ("hierarchical_depth", models.IntegerField(default=0)),
                ("cross_links", models.IntegerField(default=0)),
                ("cross_links_description", models.TextField(default="")),
                ("topological_score", models.IntegerField(default=0)),
                ("topological_score_normalized", models.FloatField(default=0.0)),
                ("topological_score_description", models.TextField(default="")),
                (
                    "concept_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topological_scoring_rubrics",
                        to="comea_app.conceptmap",
                    ),
                ),
                (
                    "evaluation_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topological_scoring_rubrics",
                        to="comea_app.cmevaluationresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="cmevaluationresult",
            name="topological_rubric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluation_results",
                to="comea_app.topologicalscoringrubric",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptmap",
            index=models.Index(
                fields=["user", "-created_at"], name="comea_app_c_user_id_30a3ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conceptmap",
            index=models.Index(
                fields=["filename"], name="comea_app_c_filenam_dbcbf6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocument",
            index=models.Index(
                fields=["user", "-created_at"], name="comea_app_r_user_id_c04733_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referencedocument",
            index=models.Index(
                fields=["filename"], name="comea_app_r_filenam_9c3324_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rubricconfiguration",
            index=models.Index(
                fields=["user", "-created_at"], name="comea_app_r_user_id_555c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rubricconfiguration",
            index=models.Index(
                fields=["name", "user"], name="comea_app_r_name_2a2a65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cmevaluationresult",
            index=models.Index(
                fields=["user", "-created_at"], name="comea_app_c_user_id_0bb750_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cmevaluationresult",
            index=models.Index(
                fields=["concept_map", "rubric"], name="comea_app_c_concept_e238cb_idx"
            ),
        ),
    ]
