# Generated by Django 5.2.7 on 2026-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comea_app", "0002_cmevaluationresult_deleted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmevaluationresult",
            name="student_other_disabilities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cmevaluationresult",
            name="student_suspected_dyslexia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalcmevaluationresult",
            name="student_other_disabilities",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcmevaluationresult",
            name="student_suspected_dyslexia",
            field=models.BooleanField(default=False),
        ),
    ]
