# Generated by Django 5.2.7 on 2026-03-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comea_app", "0003_cmevaluationresult_student_other_disabilities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltopologicalscoringrubric",
            name="topological_score_description",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topologicalscoringrubric",
            name="topological_score_description",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
