# Generated by Django 5.2.7 on 2026-04-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comea_app", "0004_alter_historicaltopologicalscoringrubric_topological_score_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmevaluationresult",
            name="comments_visual_aspects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcmevaluationresult",
            name="comments_visual_aspects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalrubricconfiguration",
            name="visual_aspects",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rubricconfiguration",
            name="visual_aspects",
            field=models.BooleanField(default=False),
        ),
    ]
