# Generated by Django 5.2.7 on 2026-04-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comea_app", "0005_rubricconfiguration_visual_aspects_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmap",
            name="edge_styles_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conceptmap",
            name="node_styles_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalconceptmap",
            name="edge_styles_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalconceptmap",
            name="node_styles_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
