# Generated by Django 5.2.7 on 2026-04-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comea_app", "0006_conceptmap_edge_styles_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptmap",
            name="concept_map_image_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalconceptmap",
            name="concept_map_image_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
